### ISSUE TITLE
Thiếu đầu số vietnamobile

### ISSUE THREAD

**Issue by nguyenngocsonit** [tonghoai/vn-phone-validator#2]
Thiếu đầu số 052 của vietnamobile. 
Hàm validate nhìn giống như bị lỗi đánh máy (dòng 71)

`validate(options = {}) {
    ...
    if (operator) this.isValidate = this.validateOperator(operators);
   ...
  }`
-> `validate(options = {}) {
    ...
    if (operator) this.isValidate = this.validateOperator(operator);
   ...
  }`

**Comment by tonghoai** [comment]
Chào bạn,
Cảm ơn bạn đã mở issue này, mình đã thêm đầu số 052 và sửa lại dòng 71 sau khi kiểm tra lại.
